name: Cityscape
main: com.sethcran.cityscape.Cityscape
version: 0.0.0.1

commands:
    city:
        description: citycommands
        usage: /city
    c:
        description: citycommands
        usage: /c
    csa:
        description: csadmincommands
        usage: /csa
    csadmin:
        description: csadmincommands
        usage: /csadmin
    player:
        description: playercommands
        usage: /player
    p:
        description: playercommands
        usage: /p
    plot:
        description: plotcommands
        usage: /plot
    chest:
        description: chestcommands
        usage: /chest