name: Cityscape
main: com.sethcran.cityscape.Cityscape
version: 0.0.0.1

commands:
    cs:
        description: commands
        usage: /cs
    cityscape:
        description: commands
        usage: /cityscape