name: Cityscape
main: com.sethcran.cityscape.Cityscape
version: 0.0.0.1

commands:
    cs:
        description: Cityscape commands
        usage: /cs
    cityscape:
    	description: Cityscape commands
    	usage: /cityscape