name: Cityscape
main: com.sethcran.cityscape.Cityscape
version: 0.0.0.1

commands:
    city:
        description: commands
        usage: /city
    c:
        description: commands
        usage: /c